### ISSUE TITLE
Travis-ci configuration could be better

### ISSUE THREAD

**Issue by wtfbbqhax** [wtfbbqhax/tremulous#1]
Sprinkle these into the .travis.yml and tidy it up

```
dist: trusty
language: cpp
compiler:
    - gcc
    - clang
env:
   - PLATFORM="mingw32"
   - PLATFORM="linux"
   - USE_<X..>=0
   - USE_<X..>=1
matrix: exclude
   - env: PLATFORM="mingw"
      compiler: clang
```

_Additional_

Have Travis build, bundle and publish tagged releases to GitHub.
