### ISSUE TITLE
Travis-ci fails to deploy build artifacts

### ISSUE THREAD

**Issue by wtfbbqhax** [wtfbbqhax/tremulous#17]
Was apart of Issue #1 

Travis-ci configuration is pretty awesome at the moment- including generation of zip archives for each platform. Currently there is a problem with the "Deploy" settings, as follows.

``` yaml
deploy:
  provider: releases
  api_key:
    secure: <expunged>
  file: 
    - build/release-darwin-x86_64.zip
    - build/release-darwin-x86.zip
    - build/release-linux-x86.zip
    - build/release-linux-x86_64.zip
    - build/release-mingw32-x86.zip
    - build/release-mingw32-x86_64.zip
  on:
    repo: wtfbbqhax/tremulous
    branch: blowfish-alpha-1
```

It looks like the _CWD_ might be wrong at the time of the deploy:

``` yaml
  adding: tremded.x86_64 (deflated 54%)
  adding: tremulous.x86_64 (deflated 50%)
  adding: renderer_opengl1_x86_64.so (deflated 53%)
  adding: renderer_opengl2_x86_64.so (deflated 54%)
  adding: base/cgamex86_64.so (deflated 55%)
  adding: base/gamex86_64.so (deflated 55%)
  adding: base/uix86_64.so (deflated 57%)
  adding: base/vm/cgame.qvm (deflated 72%)
  adding: base/vm/game.qvm (deflated 72%)
  adding: base/vm/ui.qvm (deflated 73%)
rm build/release-linux-x86_64/renderergl2/glsl/generic_fp.c build/release-linux-x86_64/renderergl2/glsl/shadowmask_fp.c build/release-linux-x86_64/renderergl2/glsl/depthblur_vp.c build/release-linux-x86_64/renderergl2/glsl/texturecolor_vp.c build/release-linux-x86_64/renderergl2/glsl/ssao_vp.c build/release-linux-x86_64/renderergl2/glsl/generic_vp.c build/release-linux-x86_64/renderergl2/glsl/lightall_fp.c build/release-linux-x86_64/renderergl2/glsl/texturecolor_fp.c build/release-linux-x86_64/renderergl2/glsl/lightall_vp.c build/release-linux-x86_64/renderergl2/glsl/bokeh_fp.c build/release-linux-x86_64/renderergl2/glsl/tonemap_fp.c build/release-linux-x86_64/renderergl2/glsl/depthblur_fp.c build/release-linux-x86_64/renderergl2/glsl/tonemap_vp.c build/release-linux-x86_64/renderergl2/glsl/calclevels4x_fp.c build/release-linux-x86_64/renderergl2/glsl/calclevels4x_vp.c build/release-linux-x86_64/renderergl2/glsl/shadowmask_vp.c build/release-linux-x86_64/renderergl2/glsl/shadowfill_fp.c build/release-linux-x86_64/renderergl2/glsl/bokeh_vp.c build/release-linux-x86_64/renderergl2/glsl/shadowfill_vp.c build/release-linux-x86_64/renderergl2/glsl/dlight_fp.c build/release-linux-x86_64/renderergl2/glsl/dlight_vp.c build/release-linux-x86_64/renderergl2/glsl/pshadow_vp.c build/release-linux-x86_64/renderergl2/glsl/down4x_fp.c build/release-linux-x86_64/renderergl2/glsl/ssao_fp.c build/release-linux-x86_64/renderergl2/glsl/down4x_vp.c build/release-linux-x86_64/renderergl2/glsl/fogpass_fp.c build/release-linux-x86_64/renderergl2/glsl/fogpass_vp.c build/release-linux-x86_64/renderergl2/glsl/pshadow_fp.c
make[2]: Leaving directory `/home/travis/build/wtfbbqhax/tremulous'
make[1]: Leaving directory `/home/travis/build/wtfbbqhax/tremulous'
Build successful.
```

The build logs also indicate that I need to set `deploy.skip_cleanup = true`:

``` yaml
Preparing deploy
Logged in as Victor Roemer
Deploying to repo: wtfbbqhax/tremulous
Current tag is: 
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment/#Uploading-Files.
Saved working directory and index state WIP on (no branch): 4e703ed Closes #15 Disable com_abnormalExit in DEBUG builds
HEAD is now at 4e703ed Closes #15 Disable com_abnormalExit in DEBUG builds

Deploying application

Already up-to-date!
HEAD detached at 4e703ed
nothing to commit, working directory clean
Dropped refs/stash@{0} (a6e9012f6c5e81df6efb689b3312ffd5b5a14391)
/home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - build/release-darwin-x86_64.zip (Errno::ENOENT)
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `new'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/octokit-4.3.0/lib/octokit/client/releases.rb:86:in `upload_asset'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:130:in `upload_file'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:111:in `block in push_app'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:102:in `each'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider/releases.rb:102:in `push_app'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `block in deploy'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/cli.rb:41:in `fold'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/provider.rb:144:in `deploy'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/cli.rb:32:in `run'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/lib/dpl/cli.rb:7:in `run'
    from /home/travis/.rvm/gems/ruby-2.2.5/gems/dpl-1.8.18/bin/dpl:5:in `<top (required)>'
    from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `load'
    from /home/travis/.rvm/gems/ruby-2.2.5/bin/dpl:23:in `<main>'
failed to deploy
```
